"""Lab persistence models. Importing this package registers every lab table on ``Base.metadata``."""

from aegis_api.lab.models.agents import Agent, AgentMessage, AgentRun, AgentStep, AgentVersion, PromptTemplate
from aegis_api.lab.models.data import Artifact, ArtifactVersion, Dataset, DatasetVersion
from aegis_api.lab.models.evaluation import EvaluationRun, LabEvaluator
from aegis_api.lab.models.execution import ComputeJob, ComputeUsage
from aegis_api.lab.models.experiments import (
    CodeSnapshot,
    ExecutionEnvironment,
    Experiment,
    ExperimentComparison,
    ExperimentMetric,
    ExperimentRun,
    ExperimentVersion,
)
from aegis_api.lab.models.failures import Failure, Lesson
from aegis_api.lab.models.governance import Approval, GovernancePolicy, GovernancePolicyVersion
from aegis_api.lab.models.hypotheses import Hypothesis, HypothesisCritique, HypothesisEvidence
from aegis_api.lab.models.knowledge import Embedding, GraphEdge, GraphNode, Memory, MemoryLink
from aegis_api.lab.models.missions import Mission, MissionVersion
from aegis_api.lab.models.org import (
    IdentityProvider,
    OrganizationSettings,
    PermissionRecord,
    Project,
    ProjectMember,
    RefreshToken,
    RolePermission,
    RoleRecord,
    ServiceAccount,
    Team,
    TeamMember,
    Workspace,
    WorkspaceMember,
)
from aegis_api.lab.models.platform import EventConsumerOffset, IdempotencyKey, LabEvent, WorkflowRun, WorkflowStep
from aegis_api.lab.models.research import ResearchEvent, ResearchSource, ResearchTask, SourceChunk, SourceDocument
from aegis_api.lab.models.strategies import (
    BenchmarkRun,
    BenchmarkSuite,
    EvolutionRun,
    Strategy,
    StrategyEvaluation,
    StrategyMutation,
    StrategyVersion,
)
from aegis_api.lab.models.tools import MCPServer, MCPTool, ToolInvocation
from aegis_api.lab.models.usage import (
    BillingPlan,
    InvoiceReference,
    ModelConfig,
    ModelUsage,
    StorageUsage,
    Subscription,
    UsageRecord,
)
from aegis_api.lab.models.verification import (
    ClaimEvidence,
    Discovery,
    DiscoveryVersion,
    MissionReport,
    Reproduction,
    ScientificClaim,
    ScientificReview,
    Verification,
    VerificationRun,
)

__all__ = [
    "Agent",
    "AgentMessage",
    "AgentRun",
    "AgentStep",
    "AgentVersion",
    "Approval",
    "Artifact",
    "ArtifactVersion",
    "BenchmarkRun",
    "BenchmarkSuite",
    "BillingPlan",
    "ClaimEvidence",
    "CodeSnapshot",
    "ComputeJob",
    "ComputeUsage",
    "Dataset",
    "DatasetVersion",
    "Discovery",
    "DiscoveryVersion",
    "Embedding",
    "EvaluationRun",
    "EventConsumerOffset",
    "EvolutionRun",
    "ExecutionEnvironment",
    "Experiment",
    "ExperimentComparison",
    "ExperimentMetric",
    "ExperimentRun",
    "ExperimentVersion",
    "Failure",
    "GovernancePolicy",
    "GovernancePolicyVersion",
    "GraphEdge",
    "GraphNode",
    "Hypothesis",
    "HypothesisCritique",
    "HypothesisEvidence",
    "IdempotencyKey",
    "IdentityProvider",
    "InvoiceReference",
    "LabEvaluator",
    "LabEvent",
    "Lesson",
    "MCPServer",
    "MCPTool",
    "Memory",
    "MemoryLink",
    "Mission",
    "MissionReport",
    "MissionVersion",
    "ModelConfig",
    "ModelUsage",
    "OrganizationSettings",
    "PermissionRecord",
    "Project",
    "ProjectMember",
    "PromptTemplate",
    "RefreshToken",
    "Reproduction",
    "ResearchEvent",
    "ResearchSource",
    "ResearchTask",
    "RolePermission",
    "RoleRecord",
    "ScientificClaim",
    "ScientificReview",
    "ServiceAccount",
    "SourceChunk",
    "SourceDocument",
    "StorageUsage",
    "Strategy",
    "StrategyEvaluation",
    "StrategyMutation",
    "StrategyVersion",
    "Subscription",
    "Team",
    "TeamMember",
    "ToolInvocation",
    "UsageRecord",
    "Verification",
    "VerificationRun",
    "WorkflowRun",
    "WorkflowStep",
    "Workspace",
    "WorkspaceMember",
]
